### ISSUE TITLE
Изменение названий объектов

### ISSUE THREAD

**Issue by makometr** [mirrin00/kitg#1]
Вообще в ангоязычном мире для обозначения вершин и рёбер используюься другие термины
![image](https://user-images.githubusercontent.com/21985069/104753242-c2b83700-5768-11eb-8f88-eabe8988e86f.png)

Это позволит меньше путаться, улучшит стандартизацию и более верятно привлечёт иностранное финансирование

**Comment by mirrin00** [comment]
Спасибо, будет учтено при дальнейших разработках. Уже перепеименовано. Однако данные реализации предполагались только для экзамена, выход в англоязычный мир не планировался
